[supervisord]
nodaemon=true

[program:quotes]
command=/usr/bin/dotnet Quotes.dll --pathBase=/Quotes
#command=/usr/bin/dotnet Quotes.dll --urls=http://0.0.0.0:50001 --pathBase=/Quotes
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/quotes.err.log
stdout_logfile=/var/log/quotes.out.log
environment=ASPNETCORE_ENVIRONMENT=Development
environment=DOTNET_PRINT_TELEMETRY_MESSAGE=false
user=root
stopsignal=INT